### ISSUE TITLE
可以查到归属地和哪一个信号

### ISSUE THREAD

**Issue by vickmiller** [hackxhj/BeautyAddressBook#2]
可以用代码查到归属地和哪一个信号，比如联通，移动还是电信的吗？

**Comment by hackxhj** [comment]
对于通讯录显示的号码来说 是可以的 用正则就可以 不同的运营商有不同的开头数字
对于本机的运营商判断 ios7好像有公开的api。

**Comment by vickmiller** [comment]
请问有没有什么demo，或者什么链接

**Comment by hackxhj** [comment]
你要判断通讯录中的号码，还是自己手机本身呢？

**Comment by vickmiller** [comment]
通讯录中的

**Comment by hackxhj** [comment]
趁着有空写的  酬和着用
NSLog(@"%@",[self getOperator:@"15361021111"]);

-(NSString_)getOperator:(NSString_)phoneNumber
{
    NSString *searchText = phoneNumber;
    NSError *error = NULL;
    NSRegularExpression *regyd = [NSRegularExpression regularExpressionWithPattern:@"(^1(3[4-9]|4[7]|5[0-27-9]|7[8]|8[2-478])\d{8}$)|(^1705\d{7}$)" options:NSRegularExpressionCaseInsensitive error:&error];

```
NSRegularExpression *reglt = [NSRegularExpression regularExpressionWithPattern:@"(^1(3[0-2]|4[5]|5[56]|7[6]|8[56])\\d{8}$)|(^1709\\d{7}$)" options:NSRegularExpressionCaseInsensitive error:&error];

NSRegularExpression *regdx = [NSRegularExpression regularExpressionWithPattern:@"(^1(33|53|77|8[019])\\d{8}$)|(^1700\\d{7}$)" options:NSRegularExpressionCaseInsensitive error:&error];

NSTextCheckingResult *resultyd = [regyd firstMatchInString:searchText options:0 range:NSMakeRange(0, [searchText length])];
if(resultyd!=nil)
    return @"移动";
NSTextCheckingResult *resultlt= [reglt firstMatchInString:searchText options:0 range:NSMakeRange(0, [searchText length])];
if(resultlt!=nil)
    return @"联通";
NSTextCheckingResult *resultdx = [regdx firstMatchInString:searchText options:0 range:NSMakeRange(0, [searchText length])];
if(resultdx!=nil)
    return @"电信";
```

   return @"未知";
}

**Comment by vickmiller** [comment]
谢谢亲，我去试下

**Comment by vickmiller** [comment]
归属地查询是要连百度的API么

**Comment by hackxhj** [comment]
嗯 有很多第三方有的。

**Comment by vickmiller** [comment]
你的方法好像只能查出电信的，移动的查不出来啊，联通的未知

**Comment by hackxhj** [comment]
什么号码段的。运营商如果有更新可以修改正则加进去。我这里测试过几个号码都是正常的。看看是什么号码 对应的看下正则表达式吧

**Comment by vickmiller** [comment]
比如这个13763005097，打印未知

**Comment by hackxhj** [comment]
好了 网上找了比较新的正则 更新了下上面的代码。以后运营商还得加号段 所以还得自己修改正则了。。

**Comment by vickmiller** [comment]
帅哥，上面的代码没有更新吧？

**Comment by hackxhj** [comment]
-(NSString_)getOperator:(NSString_)phoneNumber
{
    NSString *searchText = phoneNumber;
    NSError *error = NULL;
    NSRegularExpression *regyd = [NSRegularExpression regularExpressionWithPattern:@"(^1(3[4-9]|4[7]|5[0-27-9]|7[8]|8[2-478])\d{8}$)|(^1705\d{7}$)" options:NSRegularExpressionCaseInsensitive error:&error];

```
NSRegularExpression *reglt = [NSRegularExpression regularExpressionWithPattern:@"(^1(3[0-2]|4[5]|5[56]|7[6]|8[56])\\d{8}$)|(^1709\\d{7}$)" options:NSRegularExpressionCaseInsensitive error:&error];

NSRegularExpression *regdx = [NSRegularExpression regularExpressionWithPattern:@"(^1(33|53|77|8[019])\\d{8}$)|(^1700\\d{7}$)" options:NSRegularExpressionCaseInsensitive error:&error];

NSTextCheckingResult *resultyd = [regyd firstMatchInString:searchText options:0 range:NSMakeRange(0, [searchText length])];
if(resultyd!=nil)
    return @"移动";
NSTextCheckingResult *resultlt= [reglt firstMatchInString:searchText options:0 range:NSMakeRange(0, [searchText length])];
if(resultlt!=nil)
    return @"联通";
NSTextCheckingResult *resultdx = [regdx firstMatchInString:searchText options:0 range:NSMakeRange(0, [searchText length])];
if(resultdx!=nil)
    return @"电信";
```

   return @"未知";
}

**Comment by vickmiller** [comment]
2016-05-30 17:50:17.303 归属地查询[5282:183279] 未知
2016-05-30 17:50:17.304 归属地查询[5282:183279] 电信
2016-05-30 17:50:17.304 归属地查询[5282:183279] 未知
2016-05-30 17:50:17.305 归属地查询[5282:183279] 联通
代码还是一样啊

**Comment by hackxhj** [comment]
我测了你给的号码 还有几个 正常哦。

**Comment by vickmiller** [comment]
我认真看了一下正则表达式，真的没改什么

**Comment by hackxhj** [comment]
这里找到一个 你看看，http://www.jianshu.com/p/e8477fdccbe9

**Comment by vickmiller** [comment]
非常感谢你
